volumes:
  prometheus: {}

services:
  prometheus:
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./config/scrape_configs/scrape_prometheus.yaml:/etc/prometheus/scrape_configs/scrape_prometheus.yaml
      - ./config/scrape_configs/scrape_node.yaml:/etc/prometheus/scrape_configs/scrape_node.yaml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--web.enable-otlp-receiver'
      - '--storage.tsdb.retention.time=1y'
